### ISSUE TITLE
GitHub Actions fails with private repo: "HttpError: Bad credentials"

### ISSUE THREAD

**Issue by melo0187** [kamilkisiela/graphql-inspector#1196]
Can't get this to work with a private repo as a GitHub Action.

My workflow file `.github/workflows/graphql-inspect.yml`:
```yaml
name: GraphQL Inspector
on: [pull_request]

jobs:
  inspect-graphql:

    runs-on: ubuntu-latest

    steps:
    - name: Check GraphQL with Inspector
      uses: kamilkisiela/graphql-inspector@v1.25.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
My config file `.github/graphql-inspector.yml`:
```yaml
diff: true
schema:
  ref: master
  path: application/src/main/resources/app.graphqls
```

Action log output:
```
Run kamilkisiela/graphql-inspector@v1.25.0
  with:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name dfb13cf3e1aea1843c1a452bf8b7f34d8cf_53bdba --label 488dfb --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/mp-webapp/mp-webapp":"/github/workspace" 488dfb:13cf3e1aea1843c1a452bf8b7f34d8cf
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
ℹ  info      GraphQL Inspector started
ℹ  info      HttpError: Bad credentials 
    at response.text.then.message (/usr/local/share/.config/yarn/global/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ℹ  info      Failed to find .github/graphql-inspector.yaml file
ℹ  info      HttpError: Bad credentials 
    at response.text.then.message (/usr/local/share/.config/yarn/global/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ℹ  info      Failed to find .github/graphql-inspector.yml file
ℹ  info      Error: package.json could not be found in your project's root. 
    at Toolkit.getPackageJSON (/usr/local/share/.config/yarn/global/node_modules/actions-toolkit/lib/index.js:158:19)
    at /usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:175:37
    at step (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:45:23)
    at Object.throw (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:26:53)
    at rejected (/usr/local/share/.config/yarn/global/node_modules/@graphql-inspector/actions/dist/index.js:18:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ℹ  info      Failed to find package.json
✖  fatal     No config file
✖  fatal     Failed to find any config file
##[error]Docker run failed with exit code 1
```
I'm guessing the "Failed to find any config file" message can be ignored and is just a followup error of octokit returning "HttpError: Bad credentials".

Is my setup wrong or is this simply a bug?
Any ideas are much appreciated.

**Comment by kamilkisiela** [comment]
@melo0187 

```diff
name: GraphQL Inspector
on: [pull_request]

jobs:
  inspect-graphql:

    runs-on: ubuntu-latest

    steps:
    - name: Check GraphQL with Inspector
      uses: kamilkisiela/graphql-inspector@v1.25.0
-     with:
+     env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by kamilkisiela** [comment]
@melo0187 and let me know if it helps
