### ISSUE TITLE
Error: Cannot find module 'graphql'

### ISSUE THREAD

**Issue by ItsMrRyan** [kamilkisiela/graphql-inspector#1415]
Our ci/cd pipeline jobs starting throwing this on April 9th, 2020:
`Error: Cannot find module 'graphql' `

I was also able to reproduce locally on my machine with the following steps:
1. npm install --global @graphql-inspector/cli
2. graphql-inspector diff master_schema.graphqls schema-for-validation.graphqls

```
$ graphql-inspector diff master_schema.graphqls schema-for-validation.graphqls
 internal/modules/cjs/loader.js:983
   throw err;
   ^
 Error: Cannot find module 'graphql'
 Require stack:
 - /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-toolkit/common/index.cjs.js
 - /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-toolkit/core/index.cjs.js
 - /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/loaders/index.cjs.js
 - /usr/lib/node_modules/@graphql-inspector/cli/index.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
     at Module.require (internal/modules/cjs/loader.js:1042:19)
     at require (internal/modules/cjs/helpers.js:77:18)
     at Object.<anonymous> (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-toolkit/common/index.cjs.js:26:17)
     at Module._compile (internal/modules/cjs/loader.js:1156:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
     at Module.load (internal/modules/cjs/loader.js:1000:32)
     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
     at Module.require (internal/modules/cjs/loader.js:1042:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-toolkit/common/index.cjs.js',
     '/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-toolkit/core/index.cjs.js',
     '/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/loaders/index.cjs.js',
     '/usr/lib/node_modules/@graphql-inspector/cli/index.js'
   ]
 }

```

Any help is appreciated!  Big fan of graphql-inspector.

**Comment by kamilkisiela** [comment]
You need to install `graphql` globally too. If I would include it in `dependencies`, it will collide with other `graphql` installed packages, because of `instanceof` things.
