### ISSUE TITLE
Exported schema must be of type GraphQLSchema

### ISSUE THREAD

**Issue by Tohaker** [kamilkisiela/graphql-inspector#2041]
**Describe the bug**

When introspecting with a simple JS file to load the schema, the exported value is always deemed invalid

**To Reproduce**

```js
const { resolve } = require('path');
const { loadSchemaSync } = require('@graphql-tools/load');
const { makeExecutableSchema } = require('@graphql-tools/schema');
const { GraphQLFileLoader } = require('@graphql-tools/graphql-file-loader');

const baseSchema = resolve(__dirname, '../schemas/app.graphql');
const extraTypeSchemas = [resolve(__dirname, '../schemas/content.graphql')];

const typeDefs = loadSchemaSync([baseSchema, ...extraTypeSchemas], {
  loaders: [new GraphQLFileLoader()],
});

module.exports = makeExecutableSchema({ typeDefs });
```

```sh
graphql-inspector introspect ./src/schema.js
```

Error:

```sh
Error: Unable to load from file "/Users/gbMilBar/repos/octan/packages/graphql-gateway/src/schema.js": Exported schema must be of type GraphQLSchema, text, AST, or introspection JSON.
    at tryToLoadFromExport (/Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/code-file-loader/index.js:148:15)
    at async CodeFileLoader.handleSinglePath (/Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/code-file-loader/index.js:328:32)
    at async /Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/code-file-loader/index.js:252:32
    at async Promise.all (index 0)
    at async CodeFileLoader.load (/Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/code-file-loader/index.js:250:9)
    at async /Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/load/index.js:56:39
    at async Promise.all (index 0)
    at async loadFile (/Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/load/index.js:54:9)
    at async /Users/gbMilBar/.config/yarn/global/node_modules/@graphql-tools/load/index.js:362:25
```

Actual exported value (redacted):
```json
GraphQLSchema {
  __validationErrors: undefined,
  description: undefined,
  extensions: [Object: null prototype] {},
  astNode: { kind: 'SchemaDefinition', operationTypes: [ [Object], [Object] ] },
  extensionASTNodes: [],
  _queryType: Query,
  _mutationType: Mutation,
  _subscriptionType: undefined,
  _directives: [
    @serialize,
    @deprecatedWithMetrics,
    @cost,
    @auth,
    @include,
    @skip,
    @deprecated,
    @specifiedBy
  ],
  _typeMap: [Object: null prototype] {
    Date: Date,
    ...
    __Schema: __Schema,
    __Type: __Type,
    __TypeKind: __TypeKind,
    __Field: __Field,
    __InputValue: __InputValue,
    __EnumValue: __EnumValue,
    __Directive: __Directive,
    __DirectiveLocation: __DirectiveLocation
  },
  _subTypeMap: [Object: null prototype] {},
  _implementationsMap: [Object: null prototype] {
    ContentSection: { objects: [Array], interfaces: [] },
    ...
  }
}
```

**Expected behavior**

The CLI command to succeed

**Environment:**

- OS: MacOS 12.0.1
- `@graphql-inspector/...`: 3.0.2
- `graphql`: 15.6.1
- NodeJS: 14.17.3

**Comment by kamilkisiela** [comment]
here's a reproduction and it seems like it works https://github.com/kamilkisiela/graphql-inspector/pull/2042

**Comment by Tohaker** [comment]
I've run the command line tool against your repro and it fails with exactly the same error:
![image](https://user-images.githubusercontent.com/33665681/141274012-6852d162-62e3-49e3-b161-7db094812fb2.png)

```sh
$ graphql-inspector --version             
3.0.2
```

Am I running the command correctly?

**Comment by Tohaker** [comment]
I've found that, for some reason, the global version of `graphql-inspector` behaves differently to when it's installed via the package.json. Gonna close this, as it works fine as an `npm` script and is likely due to some global dependency issues.
