### ISSUE TITLE
--federation and --aws break diff

### ISSUE THREAD

**Issue by MichalChomo** [kamilkisiela/graphql-inspector#2051]
**Describe the bug**

When `--federation` or `--aws` flag is used, it renders `diff` command useless.

**To Reproduce**
1. Create a test file
```
$ cat << EOF > test.graphql
type Test {
  field: Invalid
}
EOF
```
2. Run diff
```
$ graphql-inspector diff test.graphql test.graphql
error Error: Unknown type "Invalid".
    at assertValidSDL (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeExecutableSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/node_modules/@graphql-tools/schema/index.js:497:26)
    at Object.mergeSchemas (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/node_modules/@graphql-tools/schema/index.js:534:12)
    at Object.loadSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.js:597:29)
Error: Unknown type "Invalid".
    at assertValidSDL (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/graphql/validation/validate.js:107:11)
    at Object.buildASTSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeExecutableSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/node_modules/@graphql-tools/schema/index.js:497:26)
    at Object.mergeSchemas (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/node_modules/@graphql-tools/schema/index.js:534:12)
    at Object.loadSchema (/Users/michal.chomo/.nvm/versions/node/v16.6.0/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.js:597:29)
```
3. Run diff with `--federation`
```
$ graphql-inspector --federation diff test.graphql test.graphql
```
4. Run diff with `--aws`
```
$ graphql-inspector --aws diff test.graphql test.graphql
```

**Expected behavior**

Error is displayed with `--federation` and `--aws` too.

**Environment:**

- OS:
- `@graphql-inspector/...`: 3.0.2
- `graphql`: 15.7.2
- NodeJS: v16.6.0

**Comment by sMorm** [comment]
I am running into the same issue on v3.0.2 as well.

**Comment by Sonamp** [comment]
Try `graphql-inspector diff test.graphql test.graphql --federation`

**Comment by revmischa** [comment]
If I run:
`graphql-inspector diff schema/generated/prod.graphql schema/generated/platform.graphql --aws`

I get:
```
error Command 'aws' not found
```
