### ISSUE TITLE
Error: Rule 'safeUnreachable' does not exist!

### ISSUE THREAD

**Issue by chrisbrake** [kamilkisiela/graphql-inspector#2063]
**Describe the bug**

On teh current release 3.0.2 I am not able to use the safeUnreachable rule at the command line.

**To Reproduce**

```
graphql-inspector diff $oldSchema $newSchema --rule safeUnreachable
error Error: Rule 'safeUnreachable' does not exist!

    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:22:27
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:19:18
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/tslib/tslib.js:113:16)
    at handler (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:12:18)
    at Object.<anonymous> (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:105:27)
    at Generator.next (<anonymous>)
Error: Rule 'safeUnreachable' does not exist!

    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:22:27
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:19:18
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@graphql-inspector/cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/tslib/tslib.js:113:16)
    at handler (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:12:18)
    at Object.<anonymous> (/usr/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-inspector/diff-command/index.js:105:27)
    at Generator.next (<anonymous>)
```

**Expected behavior**

The rule should be available for use.

**Environment:**

- OS: CentOS
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

**Comment by connorjs** [comment]
https://github.com/kamilkisiela/graphql-inspector/commit/5ef747cc1db7affdb3979831ce6a0c3e2663c60a seems to have added the `safeUnreachable` rule. I went through https://github.com/kamilkisiela/graphql-inspector/commit/5a4fd3e1de41127f1527b97b154e45801a398780 which introduced `considerUsage` rule and noticed that it added itself to `packages/core/src/diff/rules/index.ts`.

The [latest version](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/core/src/diff/rules/index.ts) ([permalink](https://github.com/kamilkisiela/graphql-inspector/blob/6b4dc24ee45efcaefdd3dbc4ff9d5754fd21b558/packages/core/src/diff/rules/index.ts)) **does not** include `safeUnreachable` here.

@kamilkisiela - Do we just need to add a re-export?

**Comment by kamilkisiela** [comment]
[v3.1.3](https://github.com/kamilkisiela/graphql-inspector/blob/master/CHANGELOG.md#v313)
