### ISSUE TITLE
extend types from apollo federation are not supported

### ISSUE THREAD

**Issue by Sonamp** [kamilkisiela/graphql-inspector#2112]
**Describe the bug**
In federation a type in a service schema can extend type from another service schema.

**To Reproduce**
For example serviceA has a type Dummy defined and serviceB is extending this type

schema1.graphql -- 
```
extend type Dummy {
    field1: String 
    field2: String
  }
```

schema2.graphql -- 
 ``` 
extend type Dummy {
      field1: String
    }
```

**Expected behavior**
on running `graphql-inspector diff schema1.graphqls schema2.graphqls --federation` the diff should be returned but returned with error
```
Error: Cannot extend type "Dummy" because it is not defined.
    at assertValidSDL (/usr/local/lib/node_modules/graphql/validation/validate.js:135:11)
    at Object.buildASTSchema (/usr/local/lib/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at makeExecutableSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/schema/index.js:495:26)
    at Object.mergeSchemas (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/schema/index.js:532:12)
    at Object.loadSchema (/usr/local/lib/node_modules/@graphql-inspector/cli/node_modules/@graphql-tools/load/index.js:622:29)
```

**Environment:**

- OS:
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS:

**Additional context**

**Comment by idanto** [comment]
I encounter the same issue if I manually remove the `extend` keyword. The diff works just fine. I guess it might be a different flag to indicate a subgraph
