### ISSUE TITLE
splice is not a function

### ISSUE THREAD

**Issue by cramhead** [kamilkisiela/graphql-inspector#2121]
**Describe the bug**

Install went smoothly, but when comparing two schemas hosted online fails with 
```
error TypeError: this.splice is not a function
    at HeadersList.append (/Users/d0c/.config/yarn/global/node_modules/cross-undici-fetch/dist/patch-headers-list.js:44:16)
    at Headers.append (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/headers.js:222:31)
    at fill (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/headers.js:68:15)
    at new Request (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/request.js:427:9)
    at new Request (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:105:13)
    at Object.fetch (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:123:24)
    at defaultAsyncFetch (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:41:29)
    at /Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:492:36
    at new ValueOrPromise (/Users/d0c/.config/yarn/global/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executor (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:460:20)
TypeError: this.splice is not a function
    at HeadersList.append (/Users/d0c/.config/yarn/global/node_modules/cross-undici-fetch/dist/patch-headers-list.js:44:16)
    at Headers.append (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/headers.js:222:31)
    at fill (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/headers.js:68:15)
    at new Request (/Users/d0c/.config/yarn/global/node_modules/undici/lib/fetch/request.js:427:9)
    at new Request (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:105:13)
    at Object.fetch (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:123:24)
    at defaultAsyncFetch (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:41:29)
    at /Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:492:36
    at new ValueOrPromise (/Users/d0c/.config/yarn/global/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executor (/Users/d0c/.config/yarn/global/node_modules/@graphql-tools/url-loader/index.js:460:20)
```

**To Reproduce**
Install with npm or yarn
![image](https://user-images.githubusercontent.com/386035/173117739-a805c4b6-015e-4756-89b1-658fa1299174.png)
Run the diff with two urls
![image](https://user-images.githubusercontent.com/386035/173117890-5387b1cf-c793-437a-8947-85ad3890d12f.png)

After installing peer dependencies there was no change in output

**Expected behavior**
A diff to standard out

**Environment:**

- OS: macOS Monterey version 12.4
- `@graphql-inspector/...`: 3.1.2
- `graphql`: 16.5.0
- NodeJS: 16.15.1

**Additional context**

**Comment by asimkhan73301** [comment]
I received the same error on version `3.1.2`. Downgrading the `@graphql-inspector/cli` to `2.9.0`  worked for me.

```
npm install --global @graphql-inspector/cli@2.9.0
```

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/graphql-inspector-2121

latest version works

**Comment by cramhead** [comment]
When I install this issue still exists. Does anything need to be pushed to npmjs?

**Comment by lillheaton** [comment]
Issue starts with version `3.1.1` using `3.1.0` works. However if using `yarn` instead of `npm` it works with the latest release... 🤷

**Comment by benrowe-chuffed** [comment]
I am having this issue too.

@kamilkisiela I tried the sample repo you provided and this still exhibits the same problem

```
git clone https://github.com/kamilkisiela/graphql-inspector-2121
cd graphql-inspector-2121
npm i
npm run test`

results in
```
~/Code/graphql-inspector-2121 (main*) » npm run test

> test
> graphql-inspector diff https://swapi-graphql.netlify.app/.netlify/functions/index https://swapi-graphql.netlify.app/.netlify/functions/index

error TypeError: this.splice is not a function
...
```

Investigating this issue further, I believe it's to do with the `cross-undici-fetch` package.

```
~/Code/graphql-inspector-2121 (main*) » npm ls cross-undici-fetch                                                                             
repro-2121@ /Users/ben/Code/graphql-inspector-2121
└─┬ @graphql-inspector/cli@3.3.0
  └─┬ @graphql-inspector/serve-command@3.3.0
    └─┬ @graphql-yoga/node@2.0.0
      ├─┬ @graphql-yoga/common@2.0.0
      │ └── cross-undici-fetch@0.1.33 deduped
      └── cross-undici-fetch@0.1.33
```
