### ISSUE TITLE
graphql-inspector cli can no longer load github-loader

### ISSUE THREAD

**Issue by benasher44** [kamilkisiela/graphql-inspector#2142]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

We upgraded from 3.1.2 to 3.3.0. After the upgrade, running a command like this no longer works:

`yarn graphql-inspector diff "git:origin/master:<path>/**/*.graphql" '<path>/**/*.graphql'`

**To Reproduce**

1. Upgrade to 3.3.0
2. Run `yarn graphql-inspector diff "git:origin/master:<path>/**/*.graphql" '<path>/**/*.graphql'`

Error:

```
yarn graphql-inspector diff "git:origin/master:./backend/src/graphql_server/**/*.graphql" 'backend/src/graphql_server/**/*.graphql'              ✔ │ 12s 
yarn run v1.22.18
$ /Users/basher/code/ashby/node_modules/.bin/graphql-inspector diff 'git:origin/master:./backend/src/graphql_server/**/*.graphql' 'backend/src/graphql_server/**/*.graphql'
Error: Cannot find module '/Users/basher/code/ashby/node_modules/@graphql-tools/github-loader/cjs/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/basher/code/ashby/node_modules/@graphql-inspector/github-loader/index.js:3:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/basher/code/ashby/node_modules/@graphql-tools/github-loader/package.json'
}
/Users/basher/code/ashby/node_modules/@graphql-inspector/loaders/index.js:22
            throw new Error(`Couldn't load ${loaderName} loader`);
                  ^

Error: Couldn't load github loader
    at LoadersRegistry.registerModule (/Users/basher/code/ashby/node_modules/@graphql-inspector/loaders/index.js:22:19)
    at /Users/basher/code/ashby/node_modules/@graphql-inspector/loaders/index.js:84:52
    at Array.forEach (<anonymous>)
    at Object.useLoaders (/Users/basher/code/ashby/node_modules/@graphql-inspector/loaders/index.js:84:20)
    at /Users/basher/code/ashby/node_modules/@graphql-inspector/cli/index.js:25:35
    at Generator.next (<anonymous>)
    at /Users/basher/code/ashby/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/basher/code/ashby/node_modules/tslib/tslib.js:114:16)
    at main (/Users/basher/code/ashby/node_modules/@graphql-inspector/cli/index.js:12:18)
```

**Expected behavior**

Emits the diff output (crashes instead)

**Environment:**

- OS: macOS 12.4 (though fails in CI, which is Ubuntu with same issue)
- `@graphql-inspector/...`: 3.3.0
- `graphql`: 16.x
- NodeJS: 16.15.0

**Additional context**

Our project is a CommonJS project (no `type` key provided in the package.json). Maybe something changed that's causing it to attempt ESM now?

**Comment by benasher44** [comment]
Hm never mind. I can't reproduce this anymore.
