### ISSUE TITLE
🐛 Validation between docs and running server fails

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [kamilkisiela/graphql-inspector#2182]
**Describe the bug**
```
TypeError: this.splice is not a function
    at HeadersList.append (<global_node_modules>\@graphql-inspector\cli\node_modules\cross-undici-fetch\dist\patch-headers-list.js:44:16)
    at Headers.append (<global_node_modules>\@graphql-inspector\cli\node_modules\undici\lib\fetch\headers.js:239:31)
    at fill (<global_node_modules>\@graphql-inspector\cli\node_modules\undici\lib\fetch\headers.js:56:15)
    at new Request (<global_node_modules>\@graphql-inspector\cli\node_modules\undici\lib\fetch\request.js:423:9)
    at Agent.fetch (<global_node_modules>\@graphql-inspector\cli\node_modules\undici\lib\fetch\index.js:116:21)
    at fetch (<global_node_modules>\@graphql-inspector\cli\node_modules\undici\index.js:95:22)
    at fetch (<global_node_modules>\@graphql-inspector\cli\node_modules\@whatwg-node\fetch\dist\create-node-ponyfill.js:145:18)
    at defaultAsyncFetch (<global_node_modules>\@graphql-inspector\cli\node_modules\@graphql-tools\url-loader\cjs\defaultAsyncFetch.js:6:30)
    at <global_node_modules>\@graphql-inspector\cli\node_modules\@graphql-tools\url-loader\cjs\index.js:205:43
    at <global_node_modules>\@graphql-inspector\cli\node_modules\value-or-promise\build\main\ValueOrPromise.js:39:44 {
  path: undefined,
  locations: undefined,
  extensions: {
    requestBody: {
      query: 'query IntrospectionQuery {\n' +
        '  __schema {\n' +
        '    queryType {\n' +
        '      name\n' +
        '    }\n' +
        '    mutationType {\n' +
        '      name\n' +
        '    }\n' +
        '    subscriptionType {\n' +
        '      name\n' +
        '    }\n' +
        '    types {\n' +
        '      ...FullType\n' +
        '    }\n' +
        '    directives {\n' +
        '      name\n' +
        '      description\n' +
        '      locations\n' +
        '      args {\n' +
        '        ...InputValue\n' +
        '      }\n' +
        '    }\n' +
        '  }\n' +
        '}\n' +
        '\n' +
        'fragment FullType on __Type {\n' +
        '  kind\n' +
        '  name\n' +
        '  description\n' +
        '  fields(includeDeprecated: true) {\n' +
        '    name\n' +
        '    description\n' +
        '    args {\n' +
        '      ...InputValue\n' +
        '    }\n' +
        '    type {\n' +
        '      ...TypeRef\n' +
        '    }\n' +
        '    isDeprecated\n' +
        '    deprecationReason\n' +
        '  }\n' +
        '  inputFields {\n' +
        '    ...InputValue\n' +
        '  }\n' +
        '  interfaces {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '  enumValues(includeDeprecated: true) {\n' +
        '    name\n' +
        '    description\n' +
        '    isDeprecated\n' +
        '    deprecationReason\n' +
        '  }\n' +
        '  possibleTypes {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '}\n' +
        '\n' +
        'fragment InputValue on __InputValue {\n' +
        '  name\n' +
        '  description\n' +
        '  type {\n' +
        '    ...TypeRef\n' +
        '  }\n' +
        '  defaultValue\n' +
        '}\n' +
        '\n' +
        'fragment TypeRef on __Type {\n' +
        '  kind\n' +
        '  name\n' +
        '  ofType {\n' +
        '    kind\n' +
        '    name\n' +
        '    ofType {\n' +
        '      kind\n' +
        '      name\n' +
        '      ofType {\n' +
        '        kind\n' +
        '        name\n' +
        '        ofType {\n' +
        '          kind\n' +
        '          name\n' +
        '          ofType {\n' +
        '            kind\n' +
        '            name\n' +
        '            ofType {\n' +
        '              kind\n' +
        '              name\n' +
        '              ofType {\n' +
        '                kind\n' +
        '                name\n' +
        '              }\n' +
        '            }\n' +
        '          }\n' +
        '        }\n' +
        '      }\n' +
        '    }\n' +
        '  }\n' +
        '}',
      variables: undefined,
      operationName: undefined,
      extensions: undefined
    }
  }
}
```

**To Reproduce** Steps to reproduce the behavior:

1. graphql-inspector validate './<some_path>/**/*.graphql' 'http://localhost:7003/graphql'

**Expected behavior**
Either a meaningful error message or a working process.

**Environment:**

- OS: Windows 10 10.0.19043
- `@graphql-inspector/cli`: @graphql-inspector/cli: 3.4.0
- `graphql` : 16.6.0
- NodeJS: 16.14.2

**Comment by TuvalSimha** [comment]
@sschneider-ihre-pvs  Still? Did you run it like that?
`graphql-inspector validate './<some_path>/**/*.graphql' 'http://localhost:7003/graphql'`

You can read the example in the docs here - [LINK](https://the-guild.dev/graphql/inspector/docs/essentials/validate)
**Usage**:
`graphql-inspector validate DOCUMENTS SCHEMA `
**Example**:
`graphql-inspector validate './documents/*.graphql' http://localhost:3000/graphql`

Only the DOCUMENTS should get single quotes

**Comment by sschneider-ihre-pvs** [comment]
`Unable to find any GraphQL type definitions for the following pointers`  at least now it fails on the first part

**Comment by TuvalSimha** [comment]
@sschneider-ihre-pvs 
Can you share more? maybe a GitHub repo? I want to try to reproduce
