### ISSUE TITLE
coverage command is broken as core was not released

### ISSUE THREAD

**Issue by velias** [kamilkisiela/graphql-inspector#2340]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

coverage command is broken as core was not released for PR #2184 

**To Reproduce** Steps to reproduce the behavior:

* run coverage commands, ends with:
```
/.../node_modules/@graphql-inspector/coverage-command/index.js:115
    logger.Logger.log(`Types covered: ${coverage.stats.numTypes > 0
                                                       ^
TypeError: Cannot read properties of undefined (reading 'numTypes')
    at renderCoverage (/.../node_modules/@graphql-inspector/coverage-command/index.js:115:56)
    at handler (/.../node_modules/@graphql-inspector/coverage-command/index.js:17:9)
    at Object.<anonymous> (/.../node_modules/@graphql-inspector/coverage-command/index.js:83:24)
    at Generator.next (<anonymous>)
    at fulfilled (/.../node_modules/tslib/tslib.js:115:62)

Node.js v18.14.0
```

**Expected behavior**

No exception ;-)

**Environment:**

- OS:
- `"@graphql-inspector/coverage-command": "^3.4.4",`

**Additional context**

**Comment by velias** [comment]
@TuvalSimha there is issue for the problem with not released core
