### ISSUE TITLE
Duplicate "graphql" modules cannot be used at the same time

### ISSUE THREAD

**Issue by FredyC** [kamilkisiela/graphql-inspector#35]
Well, this is fairly problematic, because some tools we are using are kinda unmaintained and depending on older versions. Mostly it's about the `@playlife/gql` which makes autocomplete in graphql documents possible but is heavily outdated in this regards :( The output of `yarn why graphql` is rather terrifying...

```
=> Found "graphql@0.13.2"
info Has been hoisted to "graphql"
info This module exists because it's specified in "dependencies".
=> Found "@playlyfe/gql#graphql@0.9.6"
info This module exists because "@playlyfe#gql" depends on it.
=> Found "@graphql-inspector/cli#graphql@14.0.2"
info This module exists because "@graphql-inspector#cli" depends on it.
=> Found "@graphql-inspector/api#graphql@14.0.2"
info This module exists because "@graphql-inspector#cli#@graphql-inspector#api" depends on it.
=> Found "apollo-codegen#graphql@0.9.6"
info This module exists because "@playlyfe#gql#apollo-codegen" depends on it.
=> Found "graphql-language-service-interface#graphql@0.9.6"
info This module exists because "@playlyfe#gql#graphql-language-service-interface" depends on it.
=> Found "graphql-language-service-utils#graphql@0.9.6"
info This module exists because "@playlyfe#gql#graphql-language-service-interface#graphql-language-service-utils" depends on it.=> Found "graphql-language-service-types#graphql@0.9.6"
info This module exists because "@playlyfe#gql#graphql-language-service-interface#graphql-language-service-types" depends on it.
```

I am not entirely sure how to tackle this...

```
$ D:\workspace\app\node_modules\.bin\graphql-inspector
Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version
is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data
from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (D:\workspace\app\node_modules\@graphql-inspector\api\node_modules\graphql\jsutils\instanceOf.js:37:13)
    at isSchema (D:\workspace\app\node_modules\@graphql-inspector\api\node_modules\graphql\type\schema.js:35:34)
```

**Comment by FredyC** [comment]
Hm, actually nevermind, seems that main culprit was having version `0.13.2` installed in the root of the project. Once upgraded the inspector works fine. Wondering what else gets broken. There was some reason why we needed to stay at 0.13, I just don't recall why :/
