### ISSUE TITLE
Cannot find module 'core-js/proposals/array-flat-and-flat-map'

### ISSUE THREAD

**Issue by marhaupe** [kamilkisiela/graphql-inspector#758]
Similar to #85, running this instruction:
```bash
npx graphql-inspector diff https://api.gigsmart.com/graphql/worker https://api.dev.gigsmart.com/graphql/worker
```

runs into the following error:

```bash
Cannot find module 'core-js/proposals/array-flat-and-flat-map'
```

**Comment by kamilkisiela** [comment]
@marhaupe could you share a whole error trace?

**Comment by marhaupe** [comment]
Weirdly that's the only thing that's being printed. 
```bash
~ » npx graphql-inspector diff https://api.gigsmart.com/graphql/worker https://api.dev.gigsmart.com/graphql/worker                                                                                                 
Cannot find module 'core-js/proposals/array-flat-and-flat-map'
```

Is there a `verbose`-like option I am missing?

**Comment by ka765** [comment]
Jr please call

**Comment by marhaupe** [comment]
After installing locally and without running the binary via `npx` I get the following trace:
```bash
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/marhaupe/.nvm/versions/node/v10.16.3/lib/node_modules/graphql-inspector/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I installed `graphql-inspector@0.5.1` and am running with `node --version=v10.16.3`

**Comment by sscotth** [comment]
Try `﻿npx @graphql-inspector/cli` instead.

```sh
$ npm info graphql-inspector
graphql-inspector@0.5.1 | MIT | deps: 12 | versions: 13
# ...
DEPRECATED ⚠️  - Use @graphql-inspector/cli instead
```

```
$ npm info @graphql-inspector/cli
@graphql-inspector/cli@1.26.0
```

**Comment by kamilkisiela** [comment]
@marhaupe It's `npx <package-name>` so I don't think there's a way to do it

**Comment by wzoom** [comment]
Does it have some resolution?

**Comment by sscotth** [comment]
@wzoom it used to work. Can you copy-paste your console?
