### ISSUE TITLE
CoreJS Error

### ISSUE THREAD

**Issue by jwaldrip** [kamilkisiela/graphql-inspector#85]
I am getting an error when trying to run the inspector.

```
$ graphql-inspector diff https://api.gigsmart.com/graphql/worker https://api.dev.gigsmart.com/graphql/worker
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jwaldrip/.asdf/installs/nodejs/11.9.0/.npm/lib/node_modules/@graphql-inspector/cli/node_modules/apollo-env/src/polyfills/array.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

**Comment by aeiz** [comment]
I'm getting the same. Seems like it's related to this [issue](https://github.com/apollographql/apollo-tooling/issues/962). The @graphql-inspector/cli package.json explicitly references apollo-server 2.2.6 and apollo-server-express 2.2.6. Perhaps upgrading the versions might help.

**Comment by kamilkisiela** [comment]
`0.13.1` is out, could you check if it solved the issue?

**Comment by aeiz** [comment]
@kamilkisiela, upgrading to 0.13.1 worked for me. Thanks for your quick fix!

**Comment by kamilkisiela** [comment]
Yay :)
